# Generated by Django 5.2.2 on 2025-07-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='total_votes',
        ),
    ]
