# Generated by Django 5.2.2 on 2025-07-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes_count_remove_poll_total_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='updated_at',
        ),
    ]
